### ISSUE TITLE
Include property "partOfSeries" for all types of "Article"

### ISSUE THREAD

**Issue by Meteor0id** [schemaorg/suggestions-questions-brainstorming#137]
We write articles wich are part of a series on a spesific topic. There are no seasons or episodes invloved, but we could call the group of articles ona spesific topic a series.

Thea series also has no start or end date, but has a topic as its binding factor. ("about", "description" or "name" will likely be enough to describe the series)

Articles wihtin the series might also be follow ups on previous articles, or might stand alone within the series.

"a series" in this sense can be synonymous to "a topic". The added value of regarding it as a dort of series is that they can be grouped together, and do not only hang together by simulair "about".

Alternaticely, we may introduce a whole new type named "Topic". A topic has subjects below it, a subject has articles below it. Or an article can be an immidiate child of a topic.

**Comment by RichardWallis** [comment]
See issue #7 for the context of the move from the main Schema.org [issue tracker](https://github.com/schemaorg/schemaorg/issues) to this repository.
