### ISSUE TITLE
describe physical classes of a person: eg skin type, face shape, body shape, Seasonal Color group, 3d geometry face and body. 

### ISSUE THREAD

**Issue by Torgrima** [schemaorg/suggestions-questions-brainstorming#153]
I would like to have standard labels for a person's physical appearance, then it can be easier to create product filters to matching product and the person. 

e.g if you sell glasses on the web, it will be easyer to recomend the best shape, color and size that will fit a spesific person given a spesific face shape, 3d geometry of the head and what Seasonal Color group the person belong to. 

This data will be important for cosmetic/fashion industry, headdress/hearsalong etc.

**Comment by RichardWallis** [comment]
See issue #7 for the context of the move from the main Schema.org [issue tracker](https://github.com/schemaorg/schemaorg/issues) to this repository.
