### ISSUE TITLE
online testing tool

### ISSUE THREAD

**Issue by doktorbro** [schemaorg/suggestions-questions-brainstorming#224]
i add schema-structured data to my html documents. i have tested them with the *[structured data testing tool](https://search.google.com/structured-data/testing-tool)* (created by google). now it says i should switch to the *[rich results test](https://search.google.com/test/rich-results)* (created by google). the new tool does not show me the structure nor the errors. it is useless to me. which online testing tool do you recommend?

**Comment by doktorbro** [comment]
dup for #4

**Comment by WZB13228217783** [comment]
thx
