### ISSUE TITLE
Official parser

### ISSUE THREAD

**Issue by ali-habibzadeh** [schemaorg/suggestions-questions-brainstorming#4]
Do you have or have plans for creating an official parser for schema.org? One to extract and validate the schema on string html?

**Comment by danbri** [comment]
We do not, at this stage, plan an 'official' parser. However there are a variety of freely available opensource tools that are capable of extracting JSON-LD, RDFa, Microdata etc. in most popular languages. We could do better at pointing to these, at least...

**Comment by ali-habibzadeh** [comment]
That would be great to at least know which ones you folk approve of.

**Comment by ali-habibzadeh** [comment]
@danbri Any update on pointing to libraries you consider high quality?

**Comment by danbri** [comment]
@ali-habibzadeh in Python you'd likely start with RDFLib; in Java, Any23, in Javascript, https://rdf.js.org/ 

To work with mainstram web content you'd probably also want to be parsing using a headless browser, so that markup injected by Javascript into the HTML DOM is found.

**Comment by ali-habibzadeh** [comment]
Thanks @danbri I did look at https://rdf.js.org/ before but couldn't find any component that takes HTML and outputs schema.org underlying object. Maybe I should have been more clear on what I meant by parsing. I would like to take arbitrary web pages and identify the schema.org objects they are trying to implement.

e.g. HTML to parse:

```html
HTML
<div itemscope itemtype="http://schema.org/SoftwareApplication">
  <span itemprop="name">Angry Birds</span> -

  REQUIRES <span itemprop="operatingSystem">ANDROID</span><br>
  <link itemprop="applicationCategory" href="http://schema.org/GameApplication"/>

  <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    RATING:
    <span itemprop="ratingValue">4.6</span> (
    <span itemprop="ratingCount">8864</span> ratings )
  </div>

  <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
    Price: $<span itemprop="price">1.00</span>
    <meta itemprop="priceCurrency" content="USD" />
  </div>
</div>
```

Output:

```json
SoftwareApplication": [
          {
            "@context": "http://schema.org/",
            "@type": "SoftwareApplication",
            "name": "Angry Birds",
            "operatingSystem": "ANDROID",
            "applicationCategory": "http://schema.org/GameApplication",
            "aggregateRating": {
              "@context": "http://schema.org/",
              "@type": "AggregateRating",
              "ratingValue": "4.6",
              "ratingCount": "8864"
            },
            "offers": {
              "@context": "http://schema.org/",
              "@type": "Offer",
              "price": "1.00",
              "priceCurrency": "USD"
            }
          }
        ]
```

My final goal is to validate the schema markup. Can this be achieved with https://rdf.js.org/?

**Comment by ali-habibzadeh** [comment]
In case someone else ended up here and was looking for the same thing: https://gist.github.com/ali-habibzadeh/8d29d8b41a82efcbe55fe6a5a31d7a62

Not official but not much is out there

**Comment by doktorbro** [comment]
@ali-habibzadeh how do you validate?

**Comment by ali-habibzadeh** [comment]
@doktorbro This is only the parsing logic. I have some validation stuff too but not good enough to share. But @danbri has started doing some validation here: https://github.com/google/schemarama/

Let's hope it will have multilingual support and not just for python

**Comment by doktorbro** [comment]
@ali-habibzadeh thank you for pointing to the alternative. i’m curious about @danbri’s [answer](https://github.com/google/schemarama/issues/6).

**Comment by danbri** [comment]
the parsing/extraction code in https://github.com/google/schemarama/ is related to this, but is essentially a package of existing opensource parsers. /cc @Gnomus042

**Comment by doktorbro** [comment]
@danbri so what is the tool to validate my static html documents?

**Comment by danbri** [comment]
Schemarama is a very new tool. It is not yet ready for production use (and not supported for such) but if you want to experiment with the early first release, there is currently a copy running at http://gnomus042.com/ 

Alternatively you can follow the instructions in the repo to get a working local copy. To do that you basically need to run some common Javascript utilities which compile a bundle file from source files.

**Comment by doktorbro** [comment]
@danbri your tool at gnomus042 doesn’t accept html documents.

i think i am lost. the only mature and handy tool i know ([google’s structured data testing tool](https://search.google.com/structured-data/testing-tool)) is deprecated. the alternatives are useless to me. was it a mistake to jump on the schema train?

**Comment by jvandriel** [comment]
Maybe one of these tools will help you out:
- http://linter.structured-data.org/
- https://classyschema.org/Visualisation
