### ISSUE TITLE
Godot and Metadata definition

### ISSUE THREAD

**Issue by fire** [schemaorg/suggestions-questions-brainstorming#89]
<Wikipedia\> Godot is a 2D and 3D cross-platform compatible game engine released as open source software under the MIT license. It was initially developed for several companies in Latin America before its public release.[3] The development environment runs on Linux, macOS, Windows, BSD and Haiku (both 32 and 64-bit) and can create games targeting PC, mobile and web platforms. 

Hi from a contributor from Godot Game Engine. We were looking into metadata definition for our resources.

The use-case is for metadata for Godot resource files. 
https://github.com/godotengine/godot/issues/28097 Things like license and owner.

Here is a list of our resources.

![HDWnnEc](https://user-images.githubusercontent.com/32321/56263795-352e4b80-6099-11e9-8636-639c6e0f4fbc.png)
![YSsgV4w](https://user-images.githubusercontent.com/32321/56263790-32335b00-6099-11e9-8497-43e5adbea701.png)

Is there any pointers we can look into? Is this a good use of schema.org?

Edited: 

Also there can be the ability to export the list of resources and their metadata in a project.

**Comment by RichardWallis** [comment]
See issue #7 for the context of the move from the main Schema.org [issue tracker](https://github.com/schemaorg/schemaorg/issues) to this repository.

**Comment by fire** [comment]
Since there was no replies. Will consider it closed.
